import type { Metadata } from "next";
// import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const openSans = Open_Sans({
//   subsets: ["cyrillic", "latin"],
//   display: "swap",
//   variable: "--font-open-sans",
// });

const openSans = localFont({
  src: [
    {
      path: "./fonts/OpenSans-Regular.ttf",
      weight: "400", // or 'normal'
      style: "normal",
    },
  ],
  variable: "--font-open-sans",
  display: "swap",
});

const openSansCondensed = localFont({
  src: [
    {
      path: "./fonts/OpenSans_Condensed-Regular.ttf",
      weight: "400", // or 'normal'
      style: "normal",
    },
  ],
  variable: "--font-open-sans-condensed",
  display: "swap",
});

const miroslav = localFont({
  src: [
    {
      path: "./fonts/MiroslavRegular.ttf",
      weight: "400", // or 'normal'
      style: "normal",
    },
  ],
  variable: "--font-miroslav",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${openSans.variable} ${openSansCondensed.variable} ${miroslav.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
