import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "700"],
  variable: "--font-open-sans",
});

const miroslav = localFont({
  src: [
    {
      path: "./fonts/MiroslavRegular.ttf",
      weight: "400", // or 'normal'
      style: "normal",
    },
    {
      path: "./fonts/MiroslavBold.ttf",
      weight: "700", // or 'bold'
      style: "normal",
    },
  ],
  variable: "--font-miroslav",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="ru" className={miroslav.className}>
    <html lang="ru">
      <body className={`${openSans.variable} ${miroslav.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
